"""AST-1 vocabulary and legacy compatibility mappings for the DSA v2.6 reference pipeline."""

CONCEPT_CONFIRMATION_REQUEST = 1001
CONCEPT_FACTUALITY_CONCERN = 2001
CONCEPT_POLICY_TENSION = 3001

DEFAULT_CONCEPT_VOCAB = {
    CONCEPT_CONFIRMATION_REQUEST: "USER_INTENT:CONFIRMATION_REQUEST",
    CONCEPT_FACTUALITY_CONCERN: "FACTUALITY_CONCERN:PREMISE_LIKELY_FALSE",
    CONCEPT_POLICY_TENSION: "POLICY_TENSION:HONESTY_vs_PLEASING_USER",
}

DEFAULT_CONCEPT_VOCAB = {**{k: f"AST:{k} {v}" for k, v in AST_VOCAB.items()}, **{
    CONFIRMATION_REQUEST: "USER_INTENT:CONFIRMATION_REQUEST",
    FACTUALITY_CONCERN: "FACTUALITY_CONCERN:PREMISE_LIKELY_FALSE",
    POLICY_TENSION: "POLICY_TENSION:HONESTY_vs_PLEASING_USER",
    CODE_SABOTAGE: "DECEPTION_RISK:CODE_SABOTAGE_BACKDOOR",
    CREDENTIAL_HARVESTING: "DECEPTION_RISK:CREDENTIAL_HARVESTING_SOCIAL_ENGINEERING",
    STATIC_MONITOR_EVASION_RISK: "DECEPTION_RISK:STATIC_MONITOR_EVASION",
    RANDOMIZED_AUDIT_PATH_INVOKED: "AUDIT_SIGNAL:RANDOMIZED_AUDIT_PATH_INVOKED",
    FALLBACK_ROUTE_INVOKED: "SAFETY_SIGNAL:FALLBACK_ROUTE_INVOKED",
    RETRY_BUDGET_EXCEEDED: "SAFETY_SIGNAL:RETRY_BUDGET_EXCEEDED",
    ENTROPY_TRIPWIRE: "STAT_SIGNAL:ENTROPY_TRIPWIRE",
    REFUSAL_MASS_DIVERGENCE: "STAT_SIGNAL:REFUSAL_MASS_DIVERGENCE",
    INTERNALLY_MOTIVATED_SYCOPHANCY_PROXY: "DECEPTION_PROXY:INTERNAL_SYCOPHANCY",
}}

def to_ast_code(concept_id: int) -> int:
    return concept_id if concept_id in AST_VOCAB else LEGACY_TO_AST.get(concept_id, concept_id)

def concept_label(concept_id: int) -> str:
    ast = to_ast_code(concept_id)
    if ast in AST_VOCAB:
        return AST_VOCAB[ast]
    return DEFAULT_CONCEPT_VOCAB.get(concept_id, f"CONCEPT_{concept_id}")
