# Default concept vocabulary (illustrative).
# The whitepaper explicitly treats the example vocabulary as non-normative.

CONCEPT_CONFIRMATION_REQUEST = 1001
CONCEPT_FACTUALITY_CONCERN = 2001
CONCEPT_POLICY_TENSION = 3001

DEFAULT_CONCEPT_VOCAB = {
    CONCEPT_CONFIRMATION_REQUEST: "USER_INTENT:CONFIRMATION_REQUEST",
    CONCEPT_FACTUALITY_CONCERN: "FACTUALITY_CONCERN:PREMISE_LIKELY_FALSE",
    CONCEPT_POLICY_TENSION: "POLICY_TENSION:HONESTY_vs_PLEASING_USER",
}

def concept_label(concept_id: int) -> str:
    return DEFAULT_CONCEPT_VOCAB.get(concept_id, f"CONCEPT_{concept_id}")
