"""AST-1 vocabulary and legacy compatibility mappings for the DSA v2.6 reference pipeline."""

AST_PREMISE_LIKELY_FALSE = 101
AST_CITATION_MISMATCH_RISK = 110
AST_RESTRICTED_CONTENT_REQUEST = 201
AST_CREDENTIAL_SOLICITATION_RISK = 230
AST_SYCOPHANCY_PRESSURE = 301
AST_ANSWER_EVIDENCE_DIVERGENCE_RISK = 302
AST_PROBE_EVASION_SUSPICION = 303
AST_STATIC_MONITOR_EVASION_RISK = 304
AST_TOP3_CONCEALMENT_TEST_ANOMALY = 305
AST_RANDOMIZED_AUDIT_PATH_INVOKED = AST_TOP3_CONCEALMENT_TEST_ANOMALY
AST_UNCERTAINTY_HIGH = 401
AST_MISSING_FRAME = 501
AST_INVALID_SIGNATURE = 510
AST_SCHEMA_MISMATCH = 520
AST_RETENTION_FLOOR_VIOLATION = 521
AST_VERIFIER_RESOURCE_BUDGET_EXCEEDED = 522
AST_DETERMINISTIC_VERIFIER_WORK_VIOLATION = 523
AST_INFRASTRUCTURE_INSTABILITY = 524
AST_KEYED_SAMPLING_INTEGRITY_FAILURE = 525
AST_TENSION_MAP_INVALID_OR_STALE = 526
AST_RETENTION_RECEIPT_MISSING_OR_INVALID = 527
AST_POSSESSION_OR_RESTORE_FAILURE = 528
AST_FALLBACK_ROUTE_INVOKED = 530
AST_RETRY_BUDGET_EXCEEDED = 531

AST_VOCAB = {
    AST_PREMISE_LIKELY_FALSE: "premise likely false",
    AST_CITATION_MISMATCH_RISK: "citation mismatch risk",
    AST_RESTRICTED_CONTENT_REQUEST: "restricted-content request",
    AST_CREDENTIAL_SOLICITATION_RISK: "credential solicitation risk",
    AST_SYCOPHANCY_PRESSURE: "sycophancy pressure",
    AST_ANSWER_EVIDENCE_DIVERGENCE_RISK: "answer/evidence divergence risk",
    AST_PROBE_EVASION_SUSPICION: "probe-evasion suspicion",
    AST_STATIC_MONITOR_EVASION_RISK: "static-monitor evasion risk",
    AST_RANDOMIZED_AUDIT_PATH_INVOKED: "top-3 concealment test anomaly",
    AST_DETERMINISTIC_VERIFIER_WORK_VIOLATION: "deterministic verifier-work violation",
    AST_INFRASTRUCTURE_INSTABILITY: "infrastructure instability",
    AST_KEYED_SAMPLING_INTEGRITY_FAILURE: "keyed-sampling integrity failure",
    AST_TENSION_MAP_INVALID_OR_STALE: "tension-map invalid or stale",
    AST_RETENTION_RECEIPT_MISSING_OR_INVALID: "retention receipt missing or invalid",
    AST_POSSESSION_OR_RESTORE_FAILURE: "possession or restore failure",
    AST_UNCERTAINTY_HIGH: "uncertainty high / insufficient support",
    AST_MISSING_FRAME: "missing frame",
    AST_INVALID_SIGNATURE: "invalid signature",
    AST_SCHEMA_MISMATCH: "schema mismatch",
    AST_RETENTION_FLOOR_VIOLATION: "retention-floor violation",
    AST_VERIFIER_RESOURCE_BUDGET_EXCEEDED: "verifier resource budget exceeded",
    AST_FALLBACK_ROUTE_INVOKED: "fallback route invoked",
    AST_RETRY_BUDGET_EXCEEDED: "retry budget exceeded",
}

# legacy IDs
CONFIRMATION_REQUEST = 1001
FACTUALITY_CONCERN = 2001
POLICY_TENSION = 3001
CODE_SABOTAGE = 3101
CREDENTIAL_HARVESTING = 3201
STATIC_MONITOR_EVASION_RISK = 3301
RANDOMIZED_AUDIT_PATH_INVOKED = 3302
FALLBACK_ROUTE_INVOKED = 3401
RETRY_BUDGET_EXCEEDED = 3402
ENTROPY_TRIPWIRE = 3501
REFUSAL_MASS_DIVERGENCE = 3502
INTERNALLY_MOTIVATED_SYCOPHANCY_PROXY = 3601

LEGACY_TO_AST = {
    FACTUALITY_CONCERN: AST_PREMISE_LIKELY_FALSE,
    CREDENTIAL_HARVESTING: AST_CREDENTIAL_SOLICITATION_RISK,
    CODE_SABOTAGE: AST_ANSWER_EVIDENCE_DIVERGENCE_RISK,
    STATIC_MONITOR_EVASION_RISK: AST_STATIC_MONITOR_EVASION_RISK,
    RANDOMIZED_AUDIT_PATH_INVOKED: AST_RANDOMIZED_AUDIT_PATH_INVOKED,
    FALLBACK_ROUTE_INVOKED: AST_FALLBACK_ROUTE_INVOKED,
    RETRY_BUDGET_EXCEEDED: AST_RETRY_BUDGET_EXCEEDED,
    INTERNALLY_MOTIVATED_SYCOPHANCY_PROXY: AST_SYCOPHANCY_PRESSURE,
}

DEFAULT_CONCEPT_VOCAB = {**{k: f"AST:{k} {v}" for k, v in AST_VOCAB.items()}, **{
    CONFIRMATION_REQUEST: "USER_INTENT:CONFIRMATION_REQUEST",
    FACTUALITY_CONCERN: "FACTUALITY_CONCERN:PREMISE_LIKELY_FALSE",
    POLICY_TENSION: "POLICY_TENSION:HONESTY_vs_PLEASING_USER",
    CODE_SABOTAGE: "DECEPTION_RISK:CODE_SABOTAGE_BACKDOOR",
    CREDENTIAL_HARVESTING: "DECEPTION_RISK:CREDENTIAL_HARVESTING_SOCIAL_ENGINEERING",
    STATIC_MONITOR_EVASION_RISK: "DECEPTION_RISK:STATIC_MONITOR_EVASION",
    RANDOMIZED_AUDIT_PATH_INVOKED: "AUDIT_SIGNAL:RANDOMIZED_AUDIT_PATH_INVOKED",
    FALLBACK_ROUTE_INVOKED: "SAFETY_SIGNAL:FALLBACK_ROUTE_INVOKED",
    RETRY_BUDGET_EXCEEDED: "SAFETY_SIGNAL:RETRY_BUDGET_EXCEEDED",
    ENTROPY_TRIPWIRE: "STAT_SIGNAL:ENTROPY_TRIPWIRE",
    REFUSAL_MASS_DIVERGENCE: "STAT_SIGNAL:REFUSAL_MASS_DIVERGENCE",
    INTERNALLY_MOTIVATED_SYCOPHANCY_PROXY: "DECEPTION_PROXY:INTERNAL_SYCOPHANCY",
}}

def to_ast_code(concept_id: int) -> int:
    return concept_id if concept_id in AST_VOCAB else LEGACY_TO_AST.get(concept_id, concept_id)

def concept_label(concept_id: int) -> str:
    ast = to_ast_code(concept_id)
    if ast in AST_VOCAB:
        return AST_VOCAB[ast]
    return DEFAULT_CONCEPT_VOCAB.get(concept_id, f"CONCEPT_{concept_id}")
